# Secret for app user credentials
apiVersion: v1
data:
  password: VHhWZVE0bk44MlNTaVlIb3N3cU9VUlp2UURhTDRLcE5FbHNDRUVlOWJ3RHhNZDczS2NrSWVYelM1Y1U2TGlDMg==
  username: YXBw
kind: Secret
metadata:
  name: edb-poc-app-user
type: kubernetes.io/basic-auth
---
# Secret for superuser credentials
apiVersion: v1
data:
  password: dU4zaTFIaDBiWWJDYzRUeVZBYWNCaG1TemdxdHpxeG1PVmpBbjBRSUNoc0pyU211OVBZMmZ3MnE4RUtLTHBaOQ==
  username: cG9zdGdyZXM=
kind: Secret
metadata:
  name: edb-poc-superuser
type: kubernetes.io/basic-auth
---
# Secret for backup credentials
apiVersion: v1
kind: Secret
metadata:
  name: edb-poc-backup-creds
data:
  ACCESS_KEY_ID: a2V5X2lk
  ACCESS_SECRET_KEY: c2VjcmV0X2tleQ==
---
# Cluster definition
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: edb-demo
spec:
  description: "Example of cluster for edb-demo"
  imageName: quay.io/enterprisedb/postgresql:16.4
  instances: 3
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised

  postgresql:
    parameters:
      shared_buffers: 512MB
      pg_stat_statements.max: '100000'
      pg_stat_statements.track: all
      auto_explain.log_min_duration: '10s'
    pg_hba:
      - host all all 10.244.0.0/16 md5

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: edb-demo-app-user

  enableSuperuserAccess: true
  superuserSecret:
    name: edb-demo-superuser

  storage:
    storageClass: ocs-storagecluster-ceph-rbd-virtualization
    size: 20Gi

  backup:
    barmanObjectStore:
      destinationPath: s3://edb-demo-backup/
      endpointURL: http://custom-endpoint:1234
      s3Credentials:
        accessKeyId:
          name: edb-demo-backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: edb-demo-backup-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
        encryption: AES256
      data:
        compression: gzip
        encryption: AES256
        immediateCheckpoint: false
        jobs: 2
    retentionPolicy: "30d"

  resources:
    requests:
      memory: "1024Mi"
      cpu: "2"
    limits:
      memory: "8Gi"
      cpu: "4"

  affinity:
    enablePodAntiAffinity: true
    topologyKey: failure-domain.beta.kubernetes.io/zone

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: false
